include:
  - path: ./compose/traefik.yaml
    project_directory: .
  - path: ./compose/mongo.yaml
    project_directory: .
  - path: ./plausible/compose.yaml
    project_directory: .
  - path: ./compose/whoami.yaml
    project_directory: .
  - path: ./python_sandbox/compose.yaml
    project_directory: .

services:
  fastapi:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: fastapi run main.py --host 0.0.0.0 --port 8080
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app
          ignore:
            - __pycache__/
    environment:
      CHAT_MODEL: ${CHAT_MODEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      BACKEND_API_KEY_NAME: ${BACKEND_API_KEY_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    depends_on:
      # - mongo
      - traefik
    # ports:
    #   - "8080:8080"
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.entrypoints=websecure
      - traefik.http.routers.fastapi.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.fastapi.tls=true
      - traefik.http.routers.fastapi.tls.certresolver=production
      - traefik.http.services.backend.loadbalancer.server.port=8080

  streamlit:
    build:
      context: ./streamlit/
      dockerfile: Dockerfile
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    environment:
      DOMAIN: ${DOMAIN}
      BACKEND: ${BACKEND}
      BASE_URL: ${BASE_URL}
      BACKEND_API_KEY: ${BACKEND_API_KEY}
      BACKEND_API_KEY_NAME: ${BACKEND_API_KEY_NAME}
    develop:
      watch:
        - action: sync
          path: ./streamlit
          target: /app
          ignore:
            - __pycache__/
    depends_on:
      - fastapi
    # ports:
    #   - "8501:8501"
    networks:
      - web
    labels:
      - traefik.enable=true
      # - traefik.http.routers.streamlit.entrypoints=web,websecure
      - traefik.http.routers.streamlit.entrypoints=websecure
      - traefik.http.routers.streamlit.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.www-streamlit.entrypoints=websecure
      - traefik.http.routers.www-streamlit.rule=Host(`www.${DOMAIN}`)
      - traefik.http.routers.www-streamlit.middlewares=redirect-to-non-www
      - traefik.http.routers.www-streamlit.tls.certresolver=production
      - traefik.http.routers.streamlit.tls=true
      - traefik.http.routers.streamlit.tls.certresolver=production
      - traefik.http.services.streamlit.loadbalancer.server.port=8501

      # redirect www to just aitutor
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www\\.(.*)"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$1"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true"

networks:
  web:
    external: false
