include:
  - path: ./compose/mongo.yaml
#   - path: ./streamlit/compose.yaml
#     project_directory: ../
#   - path: ./backend/compose.yaml
#     project_directory: ../

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8000:8000"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # backend:
  #   build:
  #     context: ./backend/
  #     dockerfile: Dockerfile
  #   command: fastapi dev main.py --proxy-headers --port 8080
  #   ports:
  #     - "8080:8080"

  streamlit:
    build:
      context: ./streamlit/
      dockerfile: Dockerfile
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DOMAIN: ${DOMAIN}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    develop:
      watch:
        - action: sync
          path: ./streamlit
          target: /app
          ignore:
            - __pycache__/
    ports:
      - "8501:8501"
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.services.streamlit.loadbalancer.server.port=8501

networks:
  web:
    external: false
