# include:
#   - path: ./plausible/compose.yaml
#     project_directory: .
env_file:
  - path: ./.env
    required: true # default
  - path: ./dev.env
    required: false

services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8000:8000"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  fastapi:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: fastapi dev main.py --host 0.0.0.0 --port 8080
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app
          ignore:
            - __pycache__/
    environment:
      CHAT_MODEL: ${CHAT_MODEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BACKEND_API_KEY_NAME: ${BACKEND_API_KEY_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    depends_on:
      - mongo
      - traefik
    ports:
      - "8080:8080"
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.entrypoints=web
      - traefik.http.routers.fastapi.rule=Host(`api.${DOMAIN}`)
      - traefik.http.services.backend.loadbalancer.server.port=8080

  python:
    build:
      context: ./python_sandbox/
      dockerfile: Dockerfile
    command: fastapi dev main.py --host 0.0.0.0 --port 8081
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app
          ignore:
            - __pycache__/
    depends_on:
      - traefik
      - fastapi
    ports:
      - "8081:8081"
    networks:
      - web

  mongo:
    image: mongo
    restart: unless-stopped
    # build:
    #   context: ./mongo/
    #   dockerfile: Dockerfile
    entrypoint:
      - /usr/bin/mongod
      - --bind_ip_all
    # entrypoint: sh -c "mongod --bind_ip_all && mongosh --file /tmp/mongo-dev-init.js"
    # - "--auth"
    # - "--authenticationDatabase"
    # - "admin"
    # oh my god
    # command: >
    #   bash -c "
    #   mongod --bind_ip_all;
    #   mongoimport -d aitutor -c users --file /tmp/users.json --drop;
    #   mongoimport -d aitutor -c keys --file /tmp/keys.json --drop;
    #   mongosh --file /tmp/mongo-dev-init.js;
    #   "
    ports:
      - "27017:27017"
    networks:
      - web
    volumes:
      # - ./dev/users.json:/tmp/users.json
      # - ./dev/keys.json:/tmp/keys.json
      # - ./mongo/mongo-dev-init.js:/tmp/mongo-dev-init.js
      # - ./dev/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
      # - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # in case of issues again
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

      # MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
  # mongo-express: # view from web
  #   image: mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false

  streamlit:
    build:
      context: ./streamlit/
      dockerfile: Dockerfile
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    environment:
      DOMAIN: ${DOMAIN}
      BACKEND: ${BACKEND}
      BASE_URL: ${BASE_URL}
      BACKEND_API_KEY: ${BACKEND_API_KEY}
      BACKEND_API_KEY_NAME: ${BACKEND_API_KEY_NAME}
    develop:
      watch:
        - action: sync
          path: ./streamlit
          target: /app
          ignore:
            - __pycache__/
    depends_on:
      - fastapi
    # ports:
    #   - "8501:8501"
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.streamlit.entrypoints=web
      - traefik.http.routers.streamlit.rule=Host(`${DOMAIN}`) # && !PathPrefix(`/ntfy`)
      - traefik.http.services.streamlit.loadbalancer.server.port=8501

  # ntfy:
  #   image: binwiederhier/ntfy
  #   container_name: ntfy
  #   restart: unless-stopped
  #   command:
  #     - serve
  #   environment:
  #     - TZ=UTC
  #     - NTFY_BEHIND_PROXY=true
  #   volumes:
  #     - /var/cache/ntfy:/var/cache/ntfy
  #     - /etc/ntfy:/etc/ntfy
  #   healthcheck: # optional: remember to adapt the host:port to your environment
  #     test:
  #       [
  #         "CMD-SHELL",
  #         "wget -q --tries=1 http://${DOMAIN}/ntfy/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
  #       ]
  #     interval: 60s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.ntfy.entrypoints=web
  #     - traefik.http.routers.ntfy.rule=Host(`ntfy.${DOMAIN}`) # && PathPrefix(`/ntfy`))
  #     # - traefik.http.services.ntfy.loadbalancer.server.port=8501
  #   networks:
  #     - web

networks:
  web:
    external: false

volumes:
  mongo-data:
