# include:
#   - path: ./plausible/compose.yaml
#     project_directory: .
# env_file:
#   - path: ./.env
#     required: true # default
#   - path: ./dev.env
#     required: false

services:
  traefik:
    image: traefik:3
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      # - "${HOST_PORT:-80}:80"
      - "80:80"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  fastapi:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    # command: fastapi dev main.py --host 0.0.0.0 --port 8080
    # command: /app/.venv/bin/fastapi dev main.py --host 0.0.0.0 --port 8080
    command: uv run fastapi dev main.py --host 0.0.0.0 --port 8080
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app
          ignore:
            - __pycache__/
    environment:
      CHAT_MODEL: ${CHAT_MODEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BACKEND_API_KEY_NAME: ${BACKEND_API_KEY_NAME}
      BACKEND_API_KEY: ${DEV_BACKEND_API_KEY}
      PLAUSIBLE_API_KEY: ${PLAUSIBLE_API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MONGO_APP_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_HOST: mongo
      MONGO_AUTH_SOURCE: ${MONGO_AUTH_SOURCE:-admin}
    depends_on:
      - mongo
      - traefik
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.routers.backend.rule=Host(`api.${DEV_DOMAIN}`)
      - traefik.http.services.backend.loadbalancer.server.port=8080
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://api.${DEV_DOMAIN}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s

  python:
    build:
      context: ./python_sandbox/
      dockerfile: Dockerfile
    command: uv run fastapi dev main.py --host 0.0.0.0 --port 8081
    develop:
      watch:
        - action: sync
          path: ./python_sandbox/
          target: /app
          ignore:
            - __pycache__/
    depends_on:
      - traefik
      - fastapi
    networks:
      - web

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      # These are ROOT credentials, used only by Mongo to create the root user on first launch.
      # Your .env file should define MONGO_ROOT_USERNAME and MONGO_ROOT_PASSWORD.
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-aitutor}
      # Custom variables passed to our init scripts for creating the application user and API key.
      # These are read by mongo-dev-init.js using getenv().
      MONGO_APP_USERNAME: ${MONGO_APP_USERNAME}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
      BACKEND_API_KEY: ${DEV_BACKEND_API_KEY}
    ports:
      - "27017:27017"
    networks:
      - web
    volumes:
      - mongo-data:/data/db
      - ./mongo/mongo-dev-init.js:/docker-entrypoint-initdb.d/init-db.js:ro
    # healthcheck:
    #   test: |
    #     mongosh --host 0.0.0.0 --port 27017 --eval 'db.adminCommand("ping")'
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s

  # mongo-express: # view from web
  #   image: mongo-express
  #   restart: unless-stopped
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME:-root}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-example}
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #     ME_CONFIG_BASICAUTH: false
  #     ME_CONFIG_SITE_BASEURL: /mongo-express
  #   depends_on:
  #     mongo:
  #       condition: service_healthy
  #   networks:
  #     - web
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.mongo-express.rule=Host(`${DEV_DOMAIN}`) && PathPrefix(`/mongo-express`)"
  #     - "traefik.http.routers.mongo-express.entrypoints=web"
  #     - "traefik.http.services.mongo-express.loadbalancer.server.port=8081"

  streamlit:
    build:
      context: ./streamlit/
      dockerfile: Dockerfile
    command: uv run streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    environment:
      DOMAIN: ${DEV_DOMAIN}
      BACKEND: ${BACKEND:-http://fastapi:8080/}
      BASE_URL: ${BASE_URL:-http://fastapi:8080/}
      BACKEND_API_KEY: ${DEV_BACKEND_API_KEY}
      BACKEND_API_KEY_NAME: ${BACKEND_API_KEY_NAME}
      PLAUSIBLE_API_KEY: ${PLAUSIBLE_API_KEY}
    develop:
      watch:
        - action: sync
          path: ./streamlit
          target: /app
          ignore:
            - __pycache__/
    depends_on:
      - fastapi
      - traefik
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.streamlit.entrypoints=web
      - traefik.http.routers.streamlit.rule=Host(`${DEV_DOMAIN}`)
      - traefik.http.services.streamlit.loadbalancer.server.port=8501
    # # we might have issues with using localhost in docker
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://${DEV_DOMAIN}"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 20s

  # ntfy:
  #   image: binwiederhier/ntfy
  #   container_name: ntfy
  #   restart: unless-stopped
  #   command:
  #     - serve
  #   environment:
  #     - TZ=UTC
  #     - NTFY_BEHIND_PROXY=true
  #   volumes:
  #     - /var/cache/ntfy:/var/cache/ntfy
  #     - /etc/ntfy:/etc/ntfy
  #   healthcheck: # optional: remember to adapt the host:port to your environment
  #     test:
  #       [
  #         "CMD-SHELL",
  #         "wget -q --tries=1 http://${DEV_DOMAIN}/ntfy/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
  #       ]
  #     interval: 60s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.ntfy.entrypoints=web
  #     - traefik.http.routers.ntfy.rule=Host(`ntfy.${DEV_DOMAIN}`) # && PathPrefix(`/ntfy`))
  #     # - traefik.http.services.ntfy.loadbalancer.server.port=8501
  #   networks:
  #     - web

networks:
  web:
    external: false

volumes:
  mongo-data:
