include:
  - path: ./compose/traefik.yaml
    project_directory: .
  - path: ./compose/mongo.yaml
    project_directory: .
  - path: ./plausible/compose.yaml
    project_directory: .
  - path: ./python_sandbox/compose.yaml
    project_directory: .

services:
  fastapi:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    # command: fastapi run main.py --host 0.0.0.0 --port 8080
    command: uv run fastapi run main.py --host 0.0.0.0 --port 8080
    # command: /app/.venv/bin/fastapi run main.py --host 0.0.0.0 --port 8080
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app
          ignore:
            - __pycache__/
    environment:
      CHAT_MODEL: ${CHAT_MODEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      BACKEND_API_KEY_NAME: ${BACKEND_API_KEY_NAME}
      PLAUSIBLE_API_KEY: ${PLAUSIBLE_API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    depends_on:
      traefik:
        condition: service_healthy
      mongo:
        condition: service_healthy
    # ports:
    #   - "8080:8080"
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.entrypoints=websecure
      - traefik.http.routers.fastapi.rule=Host(`api.${STG_DOMAIN}`)
      - traefik.http.routers.fastapi.tls=true
      - traefik.http.routers.fastapi.tls.certresolver=production
      - traefik.http.services.backend.loadbalancer.server.port=8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://fastapi:8080/token || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  streamlit:
    build:
      context: ./streamlit/
      dockerfile: Dockerfile
    command: uv run streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped
    environment:
      DOMAIN: ${STG_DOMAIN}
      BACKEND: ${BACKEND}
      BASE_URL: ${BASE_URL}
      BACKEND_API_KEY: ${BACKEND_API_KEY}
      BACKEND_API_KEY_NAME: ${BACKEND_API_KEY_NAME}
      PLAUSIBLE_API_KEY: ${PLAUSIBLE_API_KEY}
    develop:
      watch:
        - action: sync
          path: ./streamlit
          target: /app
          ignore:
            - __pycache__/
    depends_on:
      fastapi:
        condition: service_healthy
    # ports:
    #   - "8501:8501"
    networks:
      - web
    labels:
      - traefik.enable=true
      # - traefik.http.routers.streamlit.entrypoints=web,websecure
      - traefik.http.routers.streamlit.entrypoints=websecure
      - traefik.http.routers.streamlit.rule=Host(`${STG_DOMAIN}`)
      - traefik.http.routers.www-streamlit.entrypoints=websecure
      - traefik.http.routers.www-streamlit.rule=Host(`www.${STG_DOMAIN}`)
      - traefik.http.routers.www-streamlit.middlewares=redirect-to-non-www
      - traefik.http.routers.www-streamlit.tls.certresolver=production
      - traefik.http.routers.streamlit.tls=true
      - traefik.http.routers.streamlit.tls.certresolver=production
      - traefik.http.services.streamlit.loadbalancer.server.port=8501

      # redirect www to just aitutor
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https?://www\\.(.*)"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$$1"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true"

  testing:
    build:
      context: ./backend/
      dockerfile: testing.Dockerfile
    command: pytest
    environment:
      CHAT_MODEL: ${CHAT_MODEL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      BACKEND_API_KEY_NAME: ${BACKEND_API_KEY_NAME}
      PLAUSIBLE_API_KEY: ${PLAUSIBLE_API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - web

  # svelte:
  #   build:
  #     context: ./svelte/
  #     dockerfile: DeployDockerfile
  #   command: node -r dotenv/config /app/build/index.js
  #   depends_on:
  #     - traefik
  #     - fastapi
  #   environment:
  #     DOMAIN: ${STG_DOMAIN}
  #     API_KEY: ${API_KEY}
  #   networks:
  #     - web
  #   labels:
  #     - traefik.enable=true
  #     # - traefik.http.routers.svelte.entrypoints=web
  #     - traefik.http.routers.svelte.entrypoints=websecure
  #     - traefik.http.routers.svelte.rule=Host(`beta.${STG_DOMAIN}`)
  #     - traefik.http.routers.svelte.tls.certresolver=production
  #     # - traefik.http.middlewares.svelte-https.redirectscheme.scheme=https # WARN: untested
  #     # - traefik.http.routers.www-svelte.entrypoints=web
  #     # - traefik.http.routers.www-svelte.rule=Host(`www.${STG_DOMAIN}`)
  #     # - traefik.http.routers.www-svelte.middlewares=redirect-to-non-www
  #     - traefik.http.services.svelte.loadbalancer.server.port=3000
  #
  #     # MIDDLEWARES
  #     # - "traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^http?://www\\.(.*)"
  #     # - "traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=http://$1"
  #     # - "traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true"
  #     #

networks:
  web:
    external: false