services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8000:8000"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.aitutor.live`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      # - "traefik.http.routers.whoami.entrypoints=websecure"
      # - "traefik.http.routers.whoami.tls.certresolver=production"
    networks:
      - web

networks:
  web:
    external: false
