services:
  whoami:
    image: traefik/whoami
    environment:
      DOMAIN: ${DOMAIN}
    labels:
      - traefik.enable=true
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=production"
